public class LeadPlatformEventTriggerHelper {   
    /*public static void updateLeads(List<SmartDD__Lead_Platform_Event__e> lstLeadPlatformEvent){      
         set<Id> setLeadIds = new set<Id>();
        
        for(SmartDD__Lead_Platform_Event__e objEvent: lstLeadPlatformEvent){            
            setLeadIds.add(objEvent.SmartDD__Lead_Salesforce_ID__c);            
        }
        system.debug('LeadPlatformEventTriggerHelper setLeadIds: '+setLeadIds);
        
        if(setLeadIds.size() > 0){   
            LeadEventTriggerHelper.leadInserted(setLeadIds);
        }        
    }*/
}