@IsTest
public class SyncLeadTriggerHandlerTest {

    /*static testMethod void testMethod1() {
    	 Test.startTest();
        List<SmartDD__Dedupe_Configuration__c> lstDedupeConfig = new List<SmartDD__Dedupe_Configuration__c>();
        SmartDD__Dedupe_Configuration__c dedupeConfig = new SmartDD__Dedupe_Configuration__c();
        dedupeConfig.SmartDD__Email__c = 'test122@gmail.com';
        dedupeConfig.SmartDD__Organization_Id__c = 'test';
        lstDedupeConfig.add(dedupeConfig);
        insert lstDedupeConfig;
        
        List<SmartDD__Search_Column__c> lstSearchColumns = new List<SmartDD__Search_Column__c>();
        SmartDD__Search_Column__c searchColumn = new SmartDD__Search_Column__c();
        searchColumn.SmartDD__Search_Object_Fields__c = 'LastName';
        searchColumn.SmartDD__Object_Name__c = 'lead';
        lstSearchColumns.add(searchColumn);
        insert searchColumn;
        
       
        Test.setMock(HttpCalloutMock.class, new MockHttpResGenerator());
        List<Lead> leads = new List<Lead>();
        Lead lead = new Lead();
        lead.LastName = 'test';
        lead.company = 'test company';
        leads.add(lead);
        insert leads;
        Test.stopTest();
        System.assert(true);
        
    }*/
}